#!/bin/bash

ask()
{
  declare -g $1="$2"
  if [ -z "${!1}" ]; then
    echo "$3"
    read $1
  fi
}

if [ $1 = "transmission" ]; then
  host='cubi'
  port=9091
else
  ask host "$1" "Host:"
  ask port "$2" "Port:" 
fi

echo "Starting SSH tunnel @ $host:$port"
ssh -N -L $port:localhost:$port $host
